const menuOptions=[
  ["resolution","Resolution control"],["palette","Color swap"],["frames","Frame count"],["transparent","BG removal"],["json","JSON export"],["batch","Batch variants"],["seed","Seed randomizer"],["style","Style presets"],["layers","Layer manifest"],["brightness","Brightness"],["contrast","Contrast"],["hue","Hue shift"],["dither","Dither"],["scale","Pixel scale"],["mirror","Mirror"],["rotate","Rotate"],["trim","Trim bounds"],["shadow","Shadow"],["glow","Glow"],["download","Download all"],
  ["png","PNG export",1],["playback","Playback toggle",1],["fps","FPS control",1],["loop","Loop / ping-pong",1],["zoom","Preview zoom",1],["grid","Pixel grid",1],["undo","Undo history",1],["redo","Redo history",1],["save","Save project",1],["load","Load project",1],["randomPalette","Palette lab",1],["history","Prompt history",1]
];
const defaultState={prompt:"armored knight, 32x32, side view",seed:randomSeed(),resolution:32,palette:"neon",frames:4,transparent:true,style:"hero",brightness:100,contrast:100,hue:0,dither:false,scale:4,mirror:false,rotate:0,trim:true,shadow:true,glow:true,batch:[],fps:8,playing:true,loop:"loop",grid:true,sheetView:false,customPalette:null};
let state={...defaultState},lastSvg="",lastJson="",sheetImage=null,currentFrame=0,lastFrameTime=0,direction=1,historyStack=[],historyIndex=-1,toastTimer;
const palettes={neon:["#57e8d4","#ff4d94","#f9f871","#6c63ff"],ember:["#ff784f","#ffd166","#7d2a2a","#fff1c7"],forest:["#7ee081","#2f9c5c","#1f3f35","#d7ffd9"],royal:["#9d7dff","#4c2f91","#f7d774","#fff7d6"],mono:["#f5f7fa","#a8b0bd","#596273","#171b24"]};
const $=id=>document.getElementById(id),menuList=$("menuList"),form=$("promptForm"),promptInput=$("promptInput"),generateBtn=$("generateBtn"),canvas=$("previewCanvas"),ctx=canvas.getContext("2d"),emptyState=$("emptyState"),loadingState=$("loadingState"),errorState=$("errorState");

init();
function init(){buildMenu();bindUI();const saved=localStorage.getItem("spriteforge-autosave");if(saved){try{state={...state,...JSON.parse(saved)}}catch{}}promptInput.value=state.prompt;pushHistory();renderSprite();requestAnimationFrame(animate);refreshHistoryUI()}
function buildMenu(){menuList.innerHTML=menuOptions.map(x=>`<li tabindex="0" role="button" data-tool="${x[0]}" class="${x[2]?'new':''}">${x[1]}</li>`).join("");$("toolCount").textContent=menuOptions.length;menuList.addEventListener("click",e=>{const li=e.target.closest("li");if(li)runTool(li.dataset.tool)});menuList.addEventListener("keydown",e=>{if((e.key==="Enter"||e.key===" ")&&e.target.matches("li")){e.preventDefault();runTool(e.target.dataset.tool)}})}
function bindUI(){form.addEventListener("submit",e=>{e.preventDefault();generateSprite(promptInput.value)});document.querySelectorAll(".chip").forEach(c=>c.onclick=()=>{promptInput.value=c.dataset.prompt;generateSprite(c.dataset.prompt)});$("playBtn").onclick=togglePlayback;$("prevFrame").onclick=()=>stepFrame(-1);$("nextFrame").onclick=()=>stepFrame(1);$("fpsRange").onchange=e=>{state.fps=+e.target.value;snapshot();updateUI();autosave()};$("fpsRange").oninput=e=>{$("fpsValue").value=e.target.value;$("fpsHud").textContent=`${e.target.value} FPS`};$("sheetToggle").onclick=()=>{state.sheetView=!state.sheetView;drawPreview();updateUI();autosave()};$("gridToggle").onclick=()=>runTool("grid");$("undoBtn").onclick=undo;$("redoBtn").onclick=redo;$("saveProjectBtn").onclick=saveProject;$("randomPaletteBtn").onclick=()=>runTool("randomPalette");$("copyDataBtn").onclick=copyDataURI;$("exportPngBtn").onclick=exportPNG;$("historyBtn").onclick=()=>$("historyPanel").classList.toggle("hidden");$("clearHistory").onclick=()=>{localStorage.removeItem("spriteforge-prompts");refreshHistoryUI()};$("projectFile").onchange=importProject;document.addEventListener("keydown",shortcuts);document.addEventListener("pointermove",e=>{document.documentElement.style.setProperty("--mx",e.clientX+"px");document.documentElement.style.setProperty("--my",e.clientY+"px")},{passive:true})}
function shortcuts(e){if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?redo():undo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="y"){e.preventDefault();redo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="s"){e.preventDefault();saveProject()}if(e.code==="Space"&&document.activeElement!==promptInput){e.preventDefault();togglePlayback()}if(e.key==="ArrowLeft"&&document.activeElement!==promptInput)stepFrame(-1);if(e.key==="ArrowRight"&&document.activeElement!==promptInput)stepFrame(1)}
function generateSprite(prompt){const clean=prompt.trim();if(!clean)return showError("Describe a sprite before firing the forge.");state.prompt=clean;state.seed=randomSeed();promptInput.value=clean;addPrompt(clean);snapshot();setLoading(true);setTimeout(()=>{renderSprite();setLoading(false);setOutput("Sprite forged locally. Animation, project, SVG, PNG, and JSON outputs are ready.");toast("SPRITE FORGED")},220)}
function runTool(tool){if(["undo","redo","save","load","png","playback","history","json","download"].includes(tool)){if(tool==="undo")undo();if(tool==="redo")redo();if(tool==="save")saveProject();if(tool==="load")loadProject();if(tool==="png")exportPNG();if(tool==="playback")togglePlayback();if(tool==="history")$("historyPanel").classList.toggle("hidden");if(tool==="json")downloadText("sprite-forge-settings.json",makeJson(),"application/json");if(tool==="download")downloadAll();return}
  if(tool==="resolution")state.resolution=next(state.resolution,[16,24,32,48,64]);if(tool==="palette"){state.customPalette=null;state.palette=next(state.palette,Object.keys(palettes))}if(tool==="frames")state.frames=next(state.frames,[1,2,4,6,8]);if(tool==="transparent")state.transparent=!state.transparent;if(tool==="batch")state.batch=[...new Set([...state.batch,state.prompt,`${state.prompt} idle`,`${state.prompt} attack`,`${state.prompt} hurt`])];if(tool==="seed")state.seed=randomSeed();if(tool==="style")state.style=next(state.style,["hero","enemy","item","npc","environment"]);if(tool==="brightness")state.brightness=next(state.brightness,[75,100,125,150]);if(tool==="contrast")state.contrast=next(state.contrast,[80,100,125,150]);if(tool==="hue")state.hue=(state.hue+45)%360;if(tool==="dither")state.dither=!state.dither;if(tool==="scale"||tool==="zoom")state.scale=next(state.scale,[2,3,4,5,6]);if(tool==="mirror")state.mirror=!state.mirror;if(tool==="rotate")state.rotate=(state.rotate+90)%360;if(tool==="trim")state.trim=!state.trim;if(tool==="shadow")state.shadow=!state.shadow;if(tool==="glow")state.glow=!state.glow;if(tool==="fps")state.fps=next(state.fps,[4,6,8,12,16,24]);if(tool==="loop")state.loop=state.loop==="loop"?"pingpong":"loop";if(tool==="grid")state.grid=!state.grid;if(tool==="randomPalette")state.customPalette=randomColors();if(tool==="layers")downloadText("sprite-forge-layers.json",JSON.stringify({layers:["background","shadow","body","details","glow"],visible:{background:!state.transparent,shadow:state.shadow,body:true,details:true,glow:state.glow}},null,2),"application/json");
  snapshot();renderSprite();setOutput(`${label(tool)} applied — ${statusLine()}`);toast(`${label(tool).toUpperCase()} UPDATED`)}
function renderSprite(){const colors=state.customPalette||palettes[state.palette],size=state.resolution,cells=8,seed=hash(`${state.prompt}-${state.seed}-${state.style}`),p=[];p.push(`<svg xmlns="http://www.w3.org/2000/svg" width="${size*state.frames}" height="${size}" viewBox="0 0 ${size*state.frames} ${size}" shape-rendering="crispEdges">`);if(!state.transparent)p.push(`<rect width="100%" height="100%" fill="#101119"/>`);for(let f=0;f<state.frames;f++){const ox=f*size;if(state.shadow)p.push(`<rect x="${ox+size*.2}" y="${size*.8}" width="${size*.6}" height="${Math.max(1,size*.08)}" rx="${size*.03}" fill="#000" opacity=".32"/>`);for(let y=1;y<7;y++)for(let x=1;x<7;x++){const mx=state.mirror?7-x:x,n=hash(`${seed}-${f}-${x}-${y}`),motion=(f%2&&y>4?1:0),mask=Math.abs(x-3.5)+Math.abs(y-3.7)<4.15;if(!mask&&n%6!==0)continue;const color=colors[(n+f+y)%colors.length],op=mask?1:.72;p.push(`<rect x="${ox+mx*(size/cells)}" y="${(y+motion*.12)*(size/cells)}" width="${size/cells}" height="${size/cells}" fill="${color}" opacity="${op}"/>`);if(state.dither&&n%3===0)p.push(`<rect x="${ox+mx*(size/cells)}" y="${y*(size/cells)}" width="${size/cells/2}" height="${size/cells/2}" fill="#000" opacity=".18"/>`)}p.push(`<rect x="${ox+size*.34}" y="${size*.28}" width="${size*.1}" height="${size*.1}" fill="#090b11"/><rect x="${ox+size*.58}" y="${size*.28}" width="${size*.1}" height="${size*.1}" fill="#090b11"/>`);if(state.glow)p.push(`<rect x="${ox+1}" y="1" width="${size-2}" height="${size-2}" fill="none" stroke="${colors[0]}" opacity=".4"/>`)}p.push("</svg>");lastSvg=p.join("");lastJson=makeJson();sheetImage=new Image();sheetImage.onload=()=>{emptyState.classList.add("hidden");currentFrame=Math.min(currentFrame,state.frames-1);drawPreview()};sheetImage.src=`data:image/svg+xml;charset=utf-8,${encodeURIComponent(lastSvg)}`;updateUI();autosave()}
function drawPreview(){if(!sheetImage)return;canvas.width=360;canvas.height=360;ctx.clearRect(0,0,360,360);ctx.save();ctx.imageSmoothingEnabled=false;ctx.filter=`brightness(${state.brightness}%) contrast(${state.contrast}%) hue-rotate(${state.hue}deg)`;if(state.sheetView){const ratio=(state.resolution*state.frames)/state.resolution,w=Math.min(330,330*ratio),h=w/ratio;ctx.drawImage(sheetImage,0,0,sheetImage.naturalWidth,sheetImage.naturalHeight,(360-w)/2,(360-h)/2,w,h)}else{const pad=42,draw=360-pad*2;ctx.translate(180,180);ctx.rotate(state.rotate*Math.PI/180);ctx.drawImage(sheetImage,currentFrame*state.resolution,0,state.resolution,state.resolution,-draw/2,-draw/2,draw,draw)}ctx.restore();updateUI()}
function animate(t){if(state.playing&&!state.sheetView&&sheetImage&&t-lastFrameTime>1000/state.fps){lastFrameTime=t;if(state.loop==="pingpong"){currentFrame+=direction;if(currentFrame>=state.frames-1||currentFrame<=0)direction*=-1}else currentFrame=(currentFrame+1)%state.frames;drawPreview()}requestAnimationFrame(animate)}
function togglePlayback(){state.playing=!state.playing;$("playBtn").textContent=state.playing?"Ⅱ":"▶";toast(state.playing?"PLAYBACK ON":"PLAYBACK PAUSED")}function stepFrame(d){state.playing=false;currentFrame=(currentFrame+d+state.frames)%state.frames;drawPreview();$("playBtn").textContent="▶"}
function updateUI(){const colors=state.customPalette||palettes[state.palette];$("frameHud").textContent=`FRAME ${currentFrame+1}/${state.frames}`;$("zoomHud").textContent=`ZOOM ${state.scale}×`;$("fpsHud").textContent=`${state.fps} FPS`;$("fpsRange").value=state.fps;$("fpsValue").value=state.fps;$("sheetToggle").textContent=state.sheetView?"Sheet view":"Animation view";$("gridToggle").textContent=state.grid?"Grid on":"Grid off";$("gridOverlay").classList.toggle("off",!state.grid);canvas.style.transform=`scale(${Math.min(1.25,state.scale/4)})`;$("statResolution").textContent=`${state.resolution}×${state.resolution}`;$("statFrames").textContent=state.frames;$("statPalette").textContent=state.customPalette?"CUSTOM":state.palette.toUpperCase();$("statSeed").textContent=state.seed;$("statMode").textContent=state.style.toUpperCase();$("statMemory").textContent=`~${Math.max(1,Math.round(state.resolution*state.resolution*state.frames/1024))} KB`;$("paletteStrip").innerHTML=colors.map(c=>`<i style="background:${c}" title="${c}"></i>`).join("");$("undoBtn").disabled=historyIndex<=0;$("redoBtn").disabled=historyIndex>=historyStack.length-1}
function snapshot(){const snap=JSON.stringify(state);if(historyStack[historyIndex]===snap)return;historyStack=historyStack.slice(0,historyIndex+1);historyStack.push(snap);historyIndex=historyStack.length-1;if(historyStack.length>40){historyStack.shift();historyIndex--}}
function pushHistory(){historyStack=[JSON.stringify(state)];historyIndex=0}function undo(){if(historyIndex<=0)return toast("NOTHING TO UNDO");historyIndex--;state={...state,...JSON.parse(historyStack[historyIndex])};promptInput.value=state.prompt;renderSprite();toast("UNDO") }function redo(){if(historyIndex>=historyStack.length-1)return toast("NOTHING TO REDO");historyIndex++;state={...state,...JSON.parse(historyStack[historyIndex])};promptInput.value=state.prompt;renderSprite();toast("REDO")}
function saveProject(){autosave();downloadText("spriteforge-project.json",JSON.stringify({version:2,state},null,2),"application/json");toast("PROJECT SAVED") }function loadProject(){const local=localStorage.getItem("spriteforge-project");if(local&&confirm("Load the last locally saved project? Choose Cancel to import a file.")){applyProject(JSON.parse(local))}else $("projectFile").click()}function importProject(e){const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{applyProject(JSON.parse(reader.result))}catch{showError("That file is not a valid SpriteForge project.")}};reader.readAsText(file);e.target.value=""}function applyProject(data){snapshot();state={...defaultState,...(data.state||data)};promptInput.value=state.prompt;renderSprite();toast("PROJECT LOADED")}
function autosave(){localStorage.setItem("spriteforge-autosave",JSON.stringify(state));localStorage.setItem("spriteforge-project",JSON.stringify({version:2,state}))}
function addPrompt(p){const a=JSON.parse(localStorage.getItem("spriteforge-prompts")||"[]");localStorage.setItem("spriteforge-prompts",JSON.stringify([p,...a.filter(x=>x!==p)].slice(0,12)));refreshHistoryUI()}function refreshHistoryUI(){const a=JSON.parse(localStorage.getItem("spriteforge-prompts")||"[]");$("historyCount").textContent=a.length;$("historyList").innerHTML=a.length?a.map(p=>`<button data-prompt="${escapeHtml(p)}">${escapeHtml(p)}</button>`).join(""):"<span class='tool-output'>No recent prompts yet.</span>";$("historyList").querySelectorAll("button").forEach(b=>b.onclick=()=>{promptInput.value=b.dataset.prompt;generateSprite(b.dataset.prompt)})}
function exportPNG(){drawPreview();canvas.toBlob(blob=>downloadBlob("sprite-forge-preview.png",blob),"image/png");toast("PNG EXPORTED")}async function copyDataURI(){if(!lastSvg)return;await navigator.clipboard.writeText(`data:image/svg+xml;charset=utf-8,${encodeURIComponent(lastSvg)}`);toast("DATA URI COPIED")}
function downloadAll(){downloadText("sprite-forge-sheet.svg",lastSvg,"image/svg+xml");setTimeout(()=>downloadText("sprite-forge-settings.json",lastJson,"application/json"),120);setTimeout(exportPNG,240);setOutput("SVG sprite sheet, PNG preview, and JSON settings exported.")}
function makeJson(){return JSON.stringify({...state,paletteColors:state.customPalette||palettes[state.palette]},null,2)}function downloadText(name,text,type){downloadBlob(name,new Blob([text],{type}))}function downloadBlob(name,blob){const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
function setLoading(v){generateBtn.disabled=v;generateBtn.textContent=v?"Forging...":"Forge sprite ↯";loadingState.classList.toggle("hidden",!v)}function showError(m){errorState.textContent=m;errorState.classList.remove("hidden")}function hideError(){errorState.classList.add("hidden")}function setOutput(m){$("toolOutput").textContent=m;hideError()}function toast(m){const t=$("toast");t.textContent=m;t.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove("show"),1800)}
function label(id){return menuOptions.find(x=>x[0]===id)?.[1]||id}function statusLine(){return `${state.resolution}px · ${state.frames} frames · ${state.fps}fps · ${state.customPalette?'custom':state.palette} · seed ${state.seed}`}function next(cur,a){return a[(a.indexOf(cur)+1)%a.length]}function randomSeed(){return crypto.getRandomValues(new Uint32Array(1))[0]%900000+100000}function randomColors(){return Array.from({length:4},()=>`#${Array.from(crypto.getRandomValues(new Uint8Array(3))).map(x=>x.toString(16).padStart(2,"0")).join("")}`)}function hash(s){let v=2166136261;for(const c of String(s)){v^=c.charCodeAt(0);v=Math.imul(v,16777619)}return Math.abs(v)}function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
